import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import { Toaster } from "react-hot-toast";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { user } = await getCurrentSession();
  return (
    <html lang="en">
      <body
        className={`${inter.className}} antialiased bg-white`}
      >
        <Header user={user} />
        {children}
        <Toaster />
        <SanityLive/>
      </body>
    </html>
  );
}

export default RootLayout;